name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven
  - name: Test with Maven
    run: mvn clean test
  - name: Check Test Results
    run: |
      if [ $? -eq 0 ]; then
        echo "Tests passed"
      else
        echo "Tests failed"
        failure
      fi